language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import Markdown
script:
- echo '${GH_DEPLOY_TOKEN}' > ~/.ssh/id_rsa
- git clone 'git@github.com:dev-brasil/dev-brasil.github.io.git' theblog
- cd theblog
- git clone 'https://github.com/dev-brasil/blog-posts.git' content
- rm -rf content/.git
- make clean
- make publish
- git add .
- git commit -a -m 'okz'
- git push

